# -*- coding: utf-8 -*-
"""Histogramas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1enxWgDlP6zs7e62O2dho4b5I1Sy65Q0L
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

df = pd.read_csv('/content/NumerosAleatorios1.dat', delimiter='\t')
df2 = pd.read_csv('/content/NumerosAleatorios2.dat', delimiter='\t')
df3 = pd.read_csv('/content/RandomNCMP.dat', delimiter='\t')


# prompt: plot a histogram of the columns except n

# Assuming df is already defined as in the previous code
for col in df.columns:
    if col != 'n':
        plt.figure()  # Create a new figure for each histogram
        plt.hist(df[col], bins=10)  # Adjust bins as needed
        plt.xlabel(col)
        plt.ylabel('Frecuencia')
        plt.title(f'Histograma de {col}')
        plt.show()

# prompt: make a histogram of df2 col producto

# Assuming df2 is already defined as in the previous code
plt.figure()
plt.hist(df2['producto'], bins=10)  # Adjust bins as needed
plt.xlabel('producto')
plt.ylabel('Frecuencia')
plt.title('Histograma de producto')
plt.show()

# prompt: make a histogram of df3 col X_n

plt.figure()
plt.hist(df3['X_n'], bins=10)  # Adjust bins as needed
plt.xlabel('X_n')
plt.ylabel('Frecuencia')
plt.title('Histograma de X_n')
plt.show()
